import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatDatepickerModule,
  MatDialogModule,
  MatIconModule,
  MatInputModule,
  MatNativeDateModule,
  MatRadioModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatAutocompleteModule,
  MatListModule,
  MatExpansionModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatMenuModule,
  MatSlideToggleModule,
  MatStepperModule,
  MatButtonToggleModule,
  MatChipsModule
} from '@angular/material';
import {SvgIconsComponent} from './svg-icons/svg-icons.component';

@NgModule({
  imports: [
    MatToolbarModule,
    MatIconModule,
    MatSidenavModule,
    MatButtonModule,
    MatCheckboxModule,
    MatTabsModule,
    MatRadioModule,
    MatSelectModule,
    MatCardModule,
    MatDialogModule,
    MatButtonToggleModule,
    MatTooltipModule,
    MatTableModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatInputModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatListModule,
    MatExpansionModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatChipsModule
  ],
  exports: [
    MatToolbarModule,
    MatIconModule,
    MatSidenavModule,
    MatButtonModule,
    MatCheckboxModule,
    MatTabsModule,
    MatRadioModule,
    MatSelectModule,
    MatCardModule,
    MatDialogModule,
    MatButtonToggleModule,
    MatTooltipModule,
    MatTableModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatInputModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatListModule,
    MatExpansionModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatChipsModule,
    SvgIconsComponent
  ],
  declarations: [SvgIconsComponent]
})
export class MaterialModule {}
